// Code generated by protoc-gen-go. DO NOT EDIT.
// source: drand/control.proto

package drand

import (
	context "context"
	fmt "fmt"
	crypto "github.com/dedis/drand/protobuf/crypto"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DKGRequest struct {
	DkgGroup *GroupInfo `protobuf:"bytes,1,opt,name=dkg_group,json=dkgGroup,proto3" json:"dkg_group,omitempty"`
	IsLeader bool       `protobuf:"varint,2,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	// timeout as parsed by Golang's time.ParseDuration method.
	Timeout              string   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DKGRequest) Reset()         { *m = DKGRequest{} }
func (m *DKGRequest) String() string { return proto.CompactTextString(m) }
func (*DKGRequest) ProtoMessage()    {}
func (*DKGRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dd5961950a69ad7, []int{0}
}

func (m *DKGRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DKGRequest.Unmarshal(m, b)
}
func (m *DKGRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DKGRequest.Marshal(b, m, deterministic)
}
func (m *DKGRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DKGRequest.Merge(m, src)
}
func (m *DKGRequest) XXX_Size() int {
	return xxx_messageInfo_DKGRequest.Size(m)
}
func (m *DKGRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DKGRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DKGRequest proto.InternalMessageInfo

func (m *DKGRequest) GetDkgGroup() *GroupInfo {
	if m != nil {
		return m.DkgGroup
	}
	return nil
}

func (m *DKGRequest) GetIsLeader() bool {
	if m != nil {
		return m.IsLeader
	}
	return false
}

func (m *DKGRequest) GetTimeout() string {
	if m != nil {
		return m.Timeout
	}
	return ""
}

type DKGResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DKGResponse) Reset()         { *m = DKGResponse{} }
func (m *DKGResponse) String() string { return proto.CompactTextString(m) }
func (*DKGResponse) ProtoMessage()    {}
func (*DKGResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dd5961950a69ad7, []int{1}
}

func (m *DKGResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DKGResponse.Unmarshal(m, b)
}
func (m *DKGResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DKGResponse.Marshal(b, m, deterministic)
}
func (m *DKGResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DKGResponse.Merge(m, src)
}
func (m *DKGResponse) XXX_Size() int {
	return xxx_messageInfo_DKGResponse.Size(m)
}
func (m *DKGResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DKGResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DKGResponse proto.InternalMessageInfo

// ReshareRequest contains references to the old and new group to perform the
// resharing protocol.
type ReshareRequest struct {
	// Old group that needs to issue the shares for the new group
	// NOTE: It can be empty / nil. In that case, the drand node will try to
	// load the group he belongs to at the moment, if any, and use it as the old
	// group.
	Old      *GroupInfo `protobuf:"bytes,1,opt,name=old,proto3" json:"old,omitempty"`
	New      *GroupInfo `protobuf:"bytes,2,opt,name=new,proto3" json:"new,omitempty"`
	IsLeader bool       `protobuf:"varint,3,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	// timeout as parsed by Golang's time.ParseDuration method.
	Timeout              string   `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Entropy              string   `protobuf:"bytes,5,opt,name=entropy,proto3" json:"entropy,omitempty"`
	UserOnly             bool     `protobuf:"varint,6,opt,name=userOnly,proto3" json:"userOnly,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReshareRequest) Reset()         { *m = ReshareRequest{} }
func (m *ReshareRequest) String() string { return proto.CompactTextString(m) }
func (*ReshareRequest) ProtoMessage()    {}
func (*ReshareRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dd5961950a69ad7, []int{2}
}

func (m *ReshareRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReshareRequest.Unmarshal(m, b)
}
func (m *ReshareRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReshareRequest.Marshal(b, m, deterministic)
}
func (m *ReshareRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReshareRequest.Merge(m, src)
}
func (m *ReshareRequest) XXX_Size() int {
	return xxx_messageInfo_ReshareRequest.Size(m)
}
func (m *ReshareRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReshareRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReshareRequest proto.InternalMessageInfo

func (m *ReshareRequest) GetOld() *GroupInfo {
	if m != nil {
		return m.Old
	}
	return nil
}

func (m *ReshareRequest) GetNew() *GroupInfo {
	if m != nil {
		return m.New
	}
	return nil
}

func (m *ReshareRequest) GetIsLeader() bool {
	if m != nil {
		return m.IsLeader
	}
	return false
}

func (m *ReshareRequest) GetTimeout() string {
	if m != nil {
		return m.Timeout
	}
	return ""
}

func (m *ReshareRequest) GetEntropy() string {
	if m != nil {
		return m.Entropy
	}
	return ""
}

func (m *ReshareRequest) GetUserOnly() bool {
	if m != nil {
		return m.UserOnly
	}
	return false
}

type GroupInfo struct {
	// Types that are valid to be assigned to Location:
	//	*GroupInfo_Path
	//	*GroupInfo_Url
	Location             isGroupInfo_Location `protobuf_oneof:"location"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GroupInfo) Reset()         { *m = GroupInfo{} }
func (m *GroupInfo) String() string { return proto.CompactTextString(m) }
func (*GroupInfo) ProtoMessage()    {}
func (*GroupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dd5961950a69ad7, []int{3}
}

func (m *GroupInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupInfo.Unmarshal(m, b)
}
func (m *GroupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupInfo.Marshal(b, m, deterministic)
}
func (m *GroupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupInfo.Merge(m, src)
}
func (m *GroupInfo) XXX_Size() int {
	return xxx_messageInfo_GroupInfo.Size(m)
}
func (m *GroupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GroupInfo proto.InternalMessageInfo

type isGroupInfo_Location interface {
	isGroupInfo_Location()
}

type GroupInfo_Path struct {
	Path string `protobuf:"bytes,1,opt,name=path,proto3,oneof"`
}

type GroupInfo_Url struct {
	Url string `protobuf:"bytes,2,opt,name=url,proto3,oneof"`
}

func (*GroupInfo_Path) isGroupInfo_Location() {}

func (*GroupInfo_Url) isGroupInfo_Location() {}

func (m *GroupInfo) GetLocation() isGroupInfo_Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *GroupInfo) GetPath() string {
	if x, ok := m.GetLocation().(*GroupInfo_Path); ok {
		return x.Path
	}
	return ""
}

func (m *GroupInfo) GetUrl() string {
	if x, ok := m.GetLocation().(*GroupInfo_Url); ok {
		return x.Url
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GroupInfo) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GroupInfo_Path)(nil),
		(*GroupInfo_Url)(nil),
	}
}

type ReshareResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReshareResponse) Reset()         { *m = ReshareResponse{} }
func (m *ReshareResponse) String() string { return proto.CompactTextString(m) }
func (*ReshareResponse) ProtoMessage()    {}
func (*ReshareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dd5961950a69ad7, []int{4}
}

func (m *ReshareResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReshareResponse.Unmarshal(m, b)
}
func (m *ReshareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReshareResponse.Marshal(b, m, deterministic)
}
func (m *ReshareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReshareResponse.Merge(m, src)
}
func (m *ReshareResponse) XXX_Size() int {
	return xxx_messageInfo_ReshareResponse.Size(m)
}
func (m *ReshareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReshareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReshareResponse proto.InternalMessageInfo

// ShareRequest requests the private share of a drand node
type ShareRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShareRequest) Reset()         { *m = ShareRequest{} }
func (m *ShareRequest) String() string { return proto.CompactTextString(m) }
func (*ShareRequest) ProtoMessage()    {}
func (*ShareRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dd5961950a69ad7, []int{5}
}

func (m *ShareRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShareRequest.Unmarshal(m, b)
}
func (m *ShareRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShareRequest.Marshal(b, m, deterministic)
}
func (m *ShareRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareRequest.Merge(m, src)
}
func (m *ShareRequest) XXX_Size() int {
	return xxx_messageInfo_ShareRequest.Size(m)
}
func (m *ShareRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShareRequest proto.InternalMessageInfo

// ShareResponse holds the private share of a drand node
type ShareResponse struct {
	Index                uint32         `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Share                *crypto.Scalar `protobuf:"bytes,2,opt,name=share,proto3" json:"share,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ShareResponse) Reset()         { *m = ShareResponse{} }
func (m *ShareResponse) String() string { return proto.CompactTextString(m) }
func (*ShareResponse) ProtoMessage()    {}
func (*ShareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dd5961950a69ad7, []int{6}
}

func (m *ShareResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShareResponse.Unmarshal(m, b)
}
func (m *ShareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShareResponse.Marshal(b, m, deterministic)
}
func (m *ShareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareResponse.Merge(m, src)
}
func (m *ShareResponse) XXX_Size() int {
	return xxx_messageInfo_ShareResponse.Size(m)
}
func (m *ShareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShareResponse proto.InternalMessageInfo

func (m *ShareResponse) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ShareResponse) GetShare() *crypto.Scalar {
	if m != nil {
		return m.Share
	}
	return nil
}

type Ping struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dd5961950a69ad7, []int{7}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

type Pong struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dd5961950a69ad7, []int{8}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

// PublicKeyRequest requests the public key of a drand node
type PublicKeyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicKeyRequest) Reset()         { *m = PublicKeyRequest{} }
func (m *PublicKeyRequest) String() string { return proto.CompactTextString(m) }
func (*PublicKeyRequest) ProtoMessage()    {}
func (*PublicKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dd5961950a69ad7, []int{9}
}

func (m *PublicKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKeyRequest.Unmarshal(m, b)
}
func (m *PublicKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKeyRequest.Marshal(b, m, deterministic)
}
func (m *PublicKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKeyRequest.Merge(m, src)
}
func (m *PublicKeyRequest) XXX_Size() int {
	return xxx_messageInfo_PublicKeyRequest.Size(m)
}
func (m *PublicKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKeyRequest proto.InternalMessageInfo

// PublicKeyResponse holds the public key of a drand node
type PublicKeyResponse struct {
	PubKey               *crypto.Point `protobuf:"bytes,1,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PublicKeyResponse) Reset()         { *m = PublicKeyResponse{} }
func (m *PublicKeyResponse) String() string { return proto.CompactTextString(m) }
func (*PublicKeyResponse) ProtoMessage()    {}
func (*PublicKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dd5961950a69ad7, []int{10}
}

func (m *PublicKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKeyResponse.Unmarshal(m, b)
}
func (m *PublicKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKeyResponse.Marshal(b, m, deterministic)
}
func (m *PublicKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKeyResponse.Merge(m, src)
}
func (m *PublicKeyResponse) XXX_Size() int {
	return xxx_messageInfo_PublicKeyResponse.Size(m)
}
func (m *PublicKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKeyResponse proto.InternalMessageInfo

func (m *PublicKeyResponse) GetPubKey() *crypto.Point {
	if m != nil {
		return m.PubKey
	}
	return nil
}

// PrivateKeyRequest requests the private key of a drand node
type PrivateKeyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivateKeyRequest) Reset()         { *m = PrivateKeyRequest{} }
func (m *PrivateKeyRequest) String() string { return proto.CompactTextString(m) }
func (*PrivateKeyRequest) ProtoMessage()    {}
func (*PrivateKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dd5961950a69ad7, []int{11}
}

func (m *PrivateKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivateKeyRequest.Unmarshal(m, b)
}
func (m *PrivateKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivateKeyRequest.Marshal(b, m, deterministic)
}
func (m *PrivateKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivateKeyRequest.Merge(m, src)
}
func (m *PrivateKeyRequest) XXX_Size() int {
	return xxx_messageInfo_PrivateKeyRequest.Size(m)
}
func (m *PrivateKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivateKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrivateKeyRequest proto.InternalMessageInfo

// PrivateKeyResponse holds the private key of a drand node
type PrivateKeyResponse struct {
	PriKey               *crypto.Scalar `protobuf:"bytes,1,opt,name=priKey,proto3" json:"priKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PrivateKeyResponse) Reset()         { *m = PrivateKeyResponse{} }
func (m *PrivateKeyResponse) String() string { return proto.CompactTextString(m) }
func (*PrivateKeyResponse) ProtoMessage()    {}
func (*PrivateKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dd5961950a69ad7, []int{12}
}

func (m *PrivateKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivateKeyResponse.Unmarshal(m, b)
}
func (m *PrivateKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivateKeyResponse.Marshal(b, m, deterministic)
}
func (m *PrivateKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivateKeyResponse.Merge(m, src)
}
func (m *PrivateKeyResponse) XXX_Size() int {
	return xxx_messageInfo_PrivateKeyResponse.Size(m)
}
func (m *PrivateKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivateKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrivateKeyResponse proto.InternalMessageInfo

func (m *PrivateKeyResponse) GetPriKey() *crypto.Scalar {
	if m != nil {
		return m.PriKey
	}
	return nil
}

// CokeyRequest requests the collective key of a drand node
type CokeyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CokeyRequest) Reset()         { *m = CokeyRequest{} }
func (m *CokeyRequest) String() string { return proto.CompactTextString(m) }
func (*CokeyRequest) ProtoMessage()    {}
func (*CokeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dd5961950a69ad7, []int{13}
}

func (m *CokeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CokeyRequest.Unmarshal(m, b)
}
func (m *CokeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CokeyRequest.Marshal(b, m, deterministic)
}
func (m *CokeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CokeyRequest.Merge(m, src)
}
func (m *CokeyRequest) XXX_Size() int {
	return xxx_messageInfo_CokeyRequest.Size(m)
}
func (m *CokeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CokeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CokeyRequest proto.InternalMessageInfo

// CokeyResponse holds the collective key of a drand node
type CokeyResponse struct {
	CoKey                *crypto.Point `protobuf:"bytes,1,opt,name=coKey,proto3" json:"coKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CokeyResponse) Reset()         { *m = CokeyResponse{} }
func (m *CokeyResponse) String() string { return proto.CompactTextString(m) }
func (*CokeyResponse) ProtoMessage()    {}
func (*CokeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dd5961950a69ad7, []int{14}
}

func (m *CokeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CokeyResponse.Unmarshal(m, b)
}
func (m *CokeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CokeyResponse.Marshal(b, m, deterministic)
}
func (m *CokeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CokeyResponse.Merge(m, src)
}
func (m *CokeyResponse) XXX_Size() int {
	return xxx_messageInfo_CokeyResponse.Size(m)
}
func (m *CokeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CokeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CokeyResponse proto.InternalMessageInfo

func (m *CokeyResponse) GetCoKey() *crypto.Point {
	if m != nil {
		return m.CoKey
	}
	return nil
}

type GroupTOMLRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupTOMLRequest) Reset()         { *m = GroupTOMLRequest{} }
func (m *GroupTOMLRequest) String() string { return proto.CompactTextString(m) }
func (*GroupTOMLRequest) ProtoMessage()    {}
func (*GroupTOMLRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dd5961950a69ad7, []int{15}
}

func (m *GroupTOMLRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupTOMLRequest.Unmarshal(m, b)
}
func (m *GroupTOMLRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupTOMLRequest.Marshal(b, m, deterministic)
}
func (m *GroupTOMLRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupTOMLRequest.Merge(m, src)
}
func (m *GroupTOMLRequest) XXX_Size() int {
	return xxx_messageInfo_GroupTOMLRequest.Size(m)
}
func (m *GroupTOMLRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupTOMLRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupTOMLRequest proto.InternalMessageInfo

type GroupTOMLResponse struct {
	// TOML-encoded group file
	GroupToml            string   `protobuf:"bytes,1,opt,name=group_toml,json=groupToml,proto3" json:"group_toml,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupTOMLResponse) Reset()         { *m = GroupTOMLResponse{} }
func (m *GroupTOMLResponse) String() string { return proto.CompactTextString(m) }
func (*GroupTOMLResponse) ProtoMessage()    {}
func (*GroupTOMLResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dd5961950a69ad7, []int{16}
}

func (m *GroupTOMLResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupTOMLResponse.Unmarshal(m, b)
}
func (m *GroupTOMLResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupTOMLResponse.Marshal(b, m, deterministic)
}
func (m *GroupTOMLResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupTOMLResponse.Merge(m, src)
}
func (m *GroupTOMLResponse) XXX_Size() int {
	return xxx_messageInfo_GroupTOMLResponse.Size(m)
}
func (m *GroupTOMLResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupTOMLResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupTOMLResponse proto.InternalMessageInfo

func (m *GroupTOMLResponse) GetGroupToml() string {
	if m != nil {
		return m.GroupToml
	}
	return ""
}

func init() {
	proto.RegisterType((*DKGRequest)(nil), "drand.DKGRequest")
	proto.RegisterType((*DKGResponse)(nil), "drand.DKGResponse")
	proto.RegisterType((*ReshareRequest)(nil), "drand.ReshareRequest")
	proto.RegisterType((*GroupInfo)(nil), "drand.GroupInfo")
	proto.RegisterType((*ReshareResponse)(nil), "drand.ReshareResponse")
	proto.RegisterType((*ShareRequest)(nil), "drand.ShareRequest")
	proto.RegisterType((*ShareResponse)(nil), "drand.ShareResponse")
	proto.RegisterType((*Ping)(nil), "drand.Ping")
	proto.RegisterType((*Pong)(nil), "drand.Pong")
	proto.RegisterType((*PublicKeyRequest)(nil), "drand.PublicKeyRequest")
	proto.RegisterType((*PublicKeyResponse)(nil), "drand.PublicKeyResponse")
	proto.RegisterType((*PrivateKeyRequest)(nil), "drand.PrivateKeyRequest")
	proto.RegisterType((*PrivateKeyResponse)(nil), "drand.PrivateKeyResponse")
	proto.RegisterType((*CokeyRequest)(nil), "drand.CokeyRequest")
	proto.RegisterType((*CokeyResponse)(nil), "drand.CokeyResponse")
	proto.RegisterType((*GroupTOMLRequest)(nil), "drand.GroupTOMLRequest")
	proto.RegisterType((*GroupTOMLResponse)(nil), "drand.GroupTOMLResponse")
}

func init() { proto.RegisterFile("drand/control.proto", fileDescriptor_2dd5961950a69ad7) }

var fileDescriptor_2dd5961950a69ad7 = []byte{
	// 648 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0xdd, 0x6e, 0xd3, 0x30,
	0x18, 0x6d, 0xe9, 0xda, 0x35, 0x5f, 0xe9, 0xb6, 0x7a, 0x05, 0x42, 0x10, 0xd2, 0x14, 0xb1, 0x9f,
	0x1b, 0x5a, 0xa9, 0xc0, 0x15, 0x3f, 0x82, 0x6d, 0x62, 0x4c, 0x1d, 0x5a, 0x95, 0xed, 0x8a, 0x9b,
	0x29, 0x4d, 0xbc, 0xce, 0x9a, 0x6b, 0x07, 0xc7, 0xd9, 0xe8, 0x03, 0xf2, 0x22, 0x3c, 0x09, 0xb2,
	0xe3, 0xb8, 0x69, 0xb7, 0x5e, 0x45, 0xe7, 0x1c, 0xfb, 0x7c, 0xbf, 0x0e, 0x6c, 0xc7, 0x22, 0x64,
	0x71, 0x3f, 0xe2, 0x4c, 0x0a, 0x4e, 0x7b, 0x89, 0xe0, 0x92, 0xa3, 0xba, 0x26, 0xbd, 0x6e, 0x24,
	0x66, 0x89, 0xe4, 0x7d, 0x4c, 0xf1, 0x14, 0x33, 0x99, 0x8b, 0xbe, 0x00, 0x38, 0x1e, 0x9e, 0x04,
	0xf8, 0x77, 0x86, 0x53, 0x89, 0xde, 0x82, 0x13, 0xdf, 0x4e, 0xae, 0x26, 0x82, 0x67, 0x89, 0x5b,
	0xdd, 0xa9, 0x1e, 0xb4, 0x06, 0x5b, 0x3d, 0x7d, 0xbd, 0x77, 0xa2, 0xb8, 0x53, 0x76, 0xcd, 0x83,
	0x66, 0x7c, 0x3b, 0xd1, 0x08, 0xbd, 0x02, 0x87, 0xa4, 0x57, 0x14, 0x87, 0x31, 0x16, 0xee, 0x93,
	0x9d, 0xea, 0x41, 0x33, 0x68, 0x92, 0xf4, 0x4c, 0x63, 0xe4, 0xc2, 0xba, 0x24, 0x53, 0xcc, 0x33,
	0xe9, 0xd6, 0x76, 0xaa, 0x07, 0x4e, 0x50, 0x40, 0xbf, 0x0d, 0x2d, 0x1d, 0x33, 0x4d, 0x38, 0x4b,
	0xb1, 0xff, 0xb7, 0x0a, 0x1b, 0x01, 0x4e, 0x6f, 0x42, 0x81, 0x8b, 0x3c, 0x7c, 0xa8, 0x71, 0x1a,
	0xaf, 0xcc, 0x40, 0x89, 0xea, 0x0c, 0xc3, 0xf7, 0x3a, 0xec, 0xa3, 0x67, 0x18, 0xbe, 0x5f, 0x4c,
	0xb0, 0xb6, 0x3a, 0xc1, 0xb5, 0x85, 0x04, 0x95, 0x82, 0x55, 0x07, 0x93, 0x99, 0x5b, 0xcf, 0x15,
	0x03, 0x91, 0x07, 0xcd, 0x2c, 0xc5, 0xe2, 0x9c, 0xd1, 0x99, 0xdb, 0xc8, 0xfd, 0x0a, 0xec, 0x7f,
	0x03, 0xc7, 0x86, 0x47, 0x5d, 0x58, 0x4b, 0x42, 0x79, 0xa3, 0x4b, 0x70, 0x7e, 0x54, 0x02, 0x8d,
	0x10, 0x82, 0x5a, 0x26, 0xa8, 0xce, 0x59, 0x91, 0x0a, 0x1c, 0x02, 0x34, 0x29, 0x8f, 0x42, 0x49,
	0x38, 0xf3, 0x3b, 0xb0, 0x69, 0x3b, 0x61, 0xba, 0xb3, 0x01, 0x4f, 0x2f, 0x4a, 0xad, 0xf1, 0xcf,
	0xa0, 0x7d, 0x51, 0x3e, 0x80, 0xba, 0x50, 0x27, 0x2c, 0xc6, 0x7f, 0x74, 0xa8, 0x76, 0x90, 0x03,
	0xb4, 0x0b, 0x75, 0xed, 0x63, 0xfa, 0xb3, 0xd9, 0x2b, 0xc6, 0x7e, 0x11, 0x85, 0x34, 0x14, 0x41,
	0xae, 0xfa, 0x0d, 0x58, 0x1b, 0x11, 0x36, 0xd1, 0x5f, 0xce, 0x26, 0x3e, 0x82, 0xad, 0x51, 0x36,
	0xa6, 0x24, 0x1a, 0xe2, 0x59, 0x11, 0xf1, 0x23, 0x74, 0x4a, 0x9c, 0x89, 0xba, 0x07, 0x8d, 0x24,
	0x1b, 0x0f, 0xf1, 0xcc, 0x0c, 0x69, 0xc3, 0x06, 0x18, 0x71, 0xc2, 0x64, 0x60, 0x54, 0x7f, 0x1b,
	0x3a, 0x23, 0x41, 0xee, 0x42, 0x89, 0x4b, 0x8e, 0x9f, 0x01, 0x95, 0x49, 0x63, 0xb9, 0x0f, 0x8d,
	0x44, 0x90, 0xb9, 0xe5, 0x83, 0x9c, 0x8d, 0xac, 0x5a, 0x72, 0xc4, 0x6f, 0xe7, 0x76, 0x1f, 0xa0,
	0x6d, 0xb0, 0x71, 0x7a, 0x03, 0xf5, 0x88, 0xaf, 0xce, 0x2d, 0x17, 0x55, 0xad, 0x7a, 0x5e, 0x97,
	0xe7, 0x3f, 0xcf, 0x0a, 0xab, 0x01, 0x74, 0x4a, 0x9c, 0xb1, 0x7b, 0x0d, 0xa0, 0x5f, 0xc4, 0x95,
	0xe4, 0x53, 0x9a, 0x4f, 0x34, 0x70, 0x34, 0x73, 0xc9, 0xa7, 0x74, 0xf0, 0xaf, 0x06, 0xeb, 0x47,
	0xf9, 0x8b, 0x43, 0x7b, 0xd0, 0x54, 0xfd, 0x54, 0xbd, 0x44, 0x2d, 0xb3, 0x93, 0x8a, 0xf0, 0x2c,
	0x50, 0x5d, 0xae, 0xa0, 0x01, 0xac, 0x9f, 0x32, 0x22, 0x8f, 0x87, 0x27, 0xa8, 0x63, 0x94, 0xf9,
	0x33, 0xf4, 0x50, 0x99, 0x32, 0x7b, 0x50, 0x41, 0x5f, 0xa0, 0xa5, 0xee, 0x98, 0x05, 0x41, 0xcf,
	0xcc, 0xa1, 0xc5, 0xa7, 0xe3, 0x3d, 0x5f, 0xa6, 0xed, 0xfd, 0xf7, 0x50, 0xd7, 0x9b, 0x83, 0xb6,
	0xcd, 0x91, 0xf2, 0x5e, 0x79, 0xdd, 0x45, 0xd2, 0xde, 0xfa, 0x0a, 0x8e, 0x9d, 0x3e, 0x7a, 0x51,
	0x54, 0xb1, 0xb4, 0x23, 0x9e, 0xfb, 0x50, 0xb0, 0x0e, 0x47, 0x00, 0xf3, 0x69, 0x23, 0x7b, 0x72,
	0x79, 0x2b, 0xbc, 0x97, 0x8f, 0x28, 0xd6, 0xe4, 0x93, 0x9a, 0x31, 0xa5, 0x38, 0x92, 0xe4, 0x4e,
	0xfb, 0x14, 0x45, 0x94, 0x37, 0xc1, 0x16, 0xb1, 0xb0, 0x0e, 0x79, 0x11, 0x7a, 0xac, 0xdf, 0x09,
	0xc5, 0xb6, 0x88, 0xe5, 0xe1, 0xdb, 0x22, 0x1e, 0x6c, 0x80, 0x5f, 0x39, 0xdc, 0xff, 0xb5, 0x3b,
	0x21, 0xf2, 0x26, 0x1b, 0xf7, 0x22, 0x3e, 0xed, 0xc7, 0x38, 0x26, 0x69, 0x3f, 0xff, 0xd9, 0xea,
	0xff, 0xe8, 0x38, 0xbb, 0xce, 0xe1, 0xb8, 0xa1, 0xf1, 0xbb, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xc1, 0xf2, 0xc2, 0x5d, 0x8b, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ControlClient is the client API for Control service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControlClient interface {
	// PingPong returns an empty message. Purpose is to test the control port.
	PingPong(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error)
	// InitDKG sends information to daemon to start a fresh DKG protocol
	InitDKG(ctx context.Context, in *DKGRequest, opts ...grpc.CallOption) (*DKGResponse, error)
	// InitReshares sends all informations so that the drand node knows how to
	// proceeed during the next resharing protocol.
	InitReshare(ctx context.Context, in *ReshareRequest, opts ...grpc.CallOption) (*ReshareResponse, error)
	// Share returns the current private share used by the node
	Share(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*ShareResponse, error)
	// PublicKey returns the longterm public key of the drand node
	PublicKey(ctx context.Context, in *PublicKeyRequest, opts ...grpc.CallOption) (*PublicKeyResponse, error)
	// PrivateKey returns the longterm private key of the drand node
	PrivateKey(ctx context.Context, in *PrivateKeyRequest, opts ...grpc.CallOption) (*PrivateKeyResponse, error)
	// CollectiveKey returns the distributed public key used by the node
	CollectiveKey(ctx context.Context, in *CokeyRequest, opts ...grpc.CallOption) (*CokeyResponse, error)
	// GroupFile returns the TOML-encoded group file
	// similar to public.Group method but needed for ease of use of the
	// control functionalities
	GroupFile(ctx context.Context, in *GroupTOMLRequest, opts ...grpc.CallOption) (*GroupTOMLResponse, error)
}

type controlClient struct {
	cc *grpc.ClientConn
}

func NewControlClient(cc *grpc.ClientConn) ControlClient {
	return &controlClient{cc}
}

func (c *controlClient) PingPong(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := c.cc.Invoke(ctx, "/drand.Control/PingPong", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) InitDKG(ctx context.Context, in *DKGRequest, opts ...grpc.CallOption) (*DKGResponse, error) {
	out := new(DKGResponse)
	err := c.cc.Invoke(ctx, "/drand.Control/InitDKG", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) InitReshare(ctx context.Context, in *ReshareRequest, opts ...grpc.CallOption) (*ReshareResponse, error) {
	out := new(ReshareResponse)
	err := c.cc.Invoke(ctx, "/drand.Control/InitReshare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) Share(ctx context.Context, in *ShareRequest, opts ...grpc.CallOption) (*ShareResponse, error) {
	out := new(ShareResponse)
	err := c.cc.Invoke(ctx, "/drand.Control/Share", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) PublicKey(ctx context.Context, in *PublicKeyRequest, opts ...grpc.CallOption) (*PublicKeyResponse, error) {
	out := new(PublicKeyResponse)
	err := c.cc.Invoke(ctx, "/drand.Control/PublicKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) PrivateKey(ctx context.Context, in *PrivateKeyRequest, opts ...grpc.CallOption) (*PrivateKeyResponse, error) {
	out := new(PrivateKeyResponse)
	err := c.cc.Invoke(ctx, "/drand.Control/PrivateKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) CollectiveKey(ctx context.Context, in *CokeyRequest, opts ...grpc.CallOption) (*CokeyResponse, error) {
	out := new(CokeyResponse)
	err := c.cc.Invoke(ctx, "/drand.Control/CollectiveKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) GroupFile(ctx context.Context, in *GroupTOMLRequest, opts ...grpc.CallOption) (*GroupTOMLResponse, error) {
	out := new(GroupTOMLResponse)
	err := c.cc.Invoke(ctx, "/drand.Control/GroupFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlServer is the server API for Control service.
type ControlServer interface {
	// PingPong returns an empty message. Purpose is to test the control port.
	PingPong(context.Context, *Ping) (*Pong, error)
	// InitDKG sends information to daemon to start a fresh DKG protocol
	InitDKG(context.Context, *DKGRequest) (*DKGResponse, error)
	// InitReshares sends all informations so that the drand node knows how to
	// proceeed during the next resharing protocol.
	InitReshare(context.Context, *ReshareRequest) (*ReshareResponse, error)
	// Share returns the current private share used by the node
	Share(context.Context, *ShareRequest) (*ShareResponse, error)
	// PublicKey returns the longterm public key of the drand node
	PublicKey(context.Context, *PublicKeyRequest) (*PublicKeyResponse, error)
	// PrivateKey returns the longterm private key of the drand node
	PrivateKey(context.Context, *PrivateKeyRequest) (*PrivateKeyResponse, error)
	// CollectiveKey returns the distributed public key used by the node
	CollectiveKey(context.Context, *CokeyRequest) (*CokeyResponse, error)
	// GroupFile returns the TOML-encoded group file
	// similar to public.Group method but needed for ease of use of the
	// control functionalities
	GroupFile(context.Context, *GroupTOMLRequest) (*GroupTOMLResponse, error)
}

// UnimplementedControlServer can be embedded to have forward compatible implementations.
type UnimplementedControlServer struct {
}

func (*UnimplementedControlServer) PingPong(ctx context.Context, req *Ping) (*Pong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingPong not implemented")
}
func (*UnimplementedControlServer) InitDKG(ctx context.Context, req *DKGRequest) (*DKGResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitDKG not implemented")
}
func (*UnimplementedControlServer) InitReshare(ctx context.Context, req *ReshareRequest) (*ReshareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitReshare not implemented")
}
func (*UnimplementedControlServer) Share(ctx context.Context, req *ShareRequest) (*ShareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Share not implemented")
}
func (*UnimplementedControlServer) PublicKey(ctx context.Context, req *PublicKeyRequest) (*PublicKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublicKey not implemented")
}
func (*UnimplementedControlServer) PrivateKey(ctx context.Context, req *PrivateKeyRequest) (*PrivateKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrivateKey not implemented")
}
func (*UnimplementedControlServer) CollectiveKey(ctx context.Context, req *CokeyRequest) (*CokeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollectiveKey not implemented")
}
func (*UnimplementedControlServer) GroupFile(ctx context.Context, req *GroupTOMLRequest) (*GroupTOMLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupFile not implemented")
}

func RegisterControlServer(s *grpc.Server, srv ControlServer) {
	s.RegisterService(&_Control_serviceDesc, srv)
}

func _Control_PingPong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).PingPong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drand.Control/PingPong",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).PingPong(ctx, req.(*Ping))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_InitDKG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DKGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).InitDKG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drand.Control/InitDKG",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).InitDKG(ctx, req.(*DKGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_InitReshare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReshareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).InitReshare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drand.Control/InitReshare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).InitReshare(ctx, req.(*ReshareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_Share_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).Share(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drand.Control/Share",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).Share(ctx, req.(*ShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_PublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).PublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drand.Control/PublicKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).PublicKey(ctx, req.(*PublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_PrivateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrivateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).PrivateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drand.Control/PrivateKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).PrivateKey(ctx, req.(*PrivateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_CollectiveKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CokeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).CollectiveKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drand.Control/CollectiveKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).CollectiveKey(ctx, req.(*CokeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_GroupFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupTOMLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).GroupFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drand.Control/GroupFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).GroupFile(ctx, req.(*GroupTOMLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Control_serviceDesc = grpc.ServiceDesc{
	ServiceName: "drand.Control",
	HandlerType: (*ControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PingPong",
			Handler:    _Control_PingPong_Handler,
		},
		{
			MethodName: "InitDKG",
			Handler:    _Control_InitDKG_Handler,
		},
		{
			MethodName: "InitReshare",
			Handler:    _Control_InitReshare_Handler,
		},
		{
			MethodName: "Share",
			Handler:    _Control_Share_Handler,
		},
		{
			MethodName: "PublicKey",
			Handler:    _Control_PublicKey_Handler,
		},
		{
			MethodName: "PrivateKey",
			Handler:    _Control_PrivateKey_Handler,
		},
		{
			MethodName: "CollectiveKey",
			Handler:    _Control_CollectiveKey_Handler,
		},
		{
			MethodName: "GroupFile",
			Handler:    _Control_GroupFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "drand/control.proto",
}
